version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/.github/**/*.yml'
    commit-message:
      prefix: '[no ci]'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
      timezone: 'UTC'
